In [350]:
lst = list(range(1000000))

In [351]:
for j in range(10):
    [i*7 for i in lst]

In [352]:
# * 10 million numbers
%time for i in lst: i*7

Wall time: 327 ms


In [353]:
import numpy as np

In [354]:
arr = np.arange(1000000)

In [355]:
arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [356]:
%time arr * 7

Wall time: 0 ns


array([      0,       7,      14, ..., 6999979, 6999986, 6999993])

In [357]:
# creating nd array

In [358]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [359]:
np.zeros((7, 7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [360]:
np.ones((2, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [361]:
# creating 2's, 3's ........... infinity array
np.ones((2, 4)) * 2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [362]:
# creating my own array
lst1 = [7, 9, 5, 4, 3, 2, 1]
np.array(lst1)

array([7, 9, 5, 4, 3, 2, 1])

In [363]:
even = np.arange(0, 1000, 2)

In [364]:
odd = np.arange(1, 1000, 2)

In [365]:
even

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258,
       260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
       286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310,
       312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336,
       338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 36

In [366]:
np.arange(7, 72, 7) # 7 table

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [367]:
# it allocates memory with any numbers for the given dimensions
np.empty((2, 9))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33512376e-306, 7.56546842e-307, 8.90098127e-307,
        1.42418987e-306, 1.37961641e-306, 1.60220528e-306],
       [1.24611266e-306, 9.34598925e-307, 1.24612081e-306,
        1.11260755e-306, 1.60220393e-306, 1.51320640e-306,
        9.34609790e-307, 1.86921279e-306, 1.24610723e-306]])

In [368]:
a = np.ones((2, 4), dtype='int')

In [369]:
a.shape

(2, 4)

In [370]:
a.ndim

2

a

In [371]:
a.dtype

dtype('int32')

In [372]:
a = a.astype('float')

In [373]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [374]:
a.dtype

dtype('float64')

# RESHAPING

In [375]:
x = np.ones((4, 5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [376]:
x.reshape((5, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [377]:
x.reshape((2, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [378]:
x.reshape((10, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [379]:
x.reshape(2,5,2)

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [380]:
x.reshape(5, 2, 2)

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [381]:
x.reshape(5, 2, 2)

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

# Vectorization

In [382]:
x = np.array([7,8,9])

In [383]:
# multiply with scalar
x * 7

array([49, 56, 63])

In [384]:
y = np.array([5, 9,8])

In [385]:
# element-wise multiplication
x*y

array([35, 72, 72])

In [386]:
x+y

array([12, 17, 17])

In [387]:
x-y

array([ 2, -1,  1])

In [388]:
# 2 dim array
lst1 = [2, 3, 4]
lst2 = [5, 6, 1]
np.array((lst1, lst2))

array([[2, 3, 4],
       [5, 6, 1]])

In [389]:
np.array([[2, 4], [3, 2]])

array([[2, 4],
       [3, 2]])

# Comparison

In [390]:
x = np.array([-5, 7, 8, 1, 33, 0, 3])
x > 2

array([False,  True,  True, False,  True, False,  True])

In [391]:
x[x>2]

array([ 7,  8, 33,  3])

In [392]:
name = np.array(['tuna', 'toaster', 'courage', 'fred', 'johny', 'shet', 'kahn'])

In [393]:
name

array(['tuna', 'toaster', 'courage', 'fred', 'johny', 'shet', 'kahn'],
      dtype='<U7')

In [394]:
marks = np.array([90, 23, 66, 21, 88, 98, 99])

In [395]:
marks

array([90, 23, 66, 21, 88, 98, 99])

In [396]:
name[marks >= 60]

array(['tuna', 'courage', 'johny', 'shet', 'kahn'], dtype='<U7')

In [397]:
fee = np.array(['submitted', 'not submitted', 'not submitted',  'submitted', 'not submitted', 'submitted', 'submitted'])

In [398]:
name[fee=='submitted']

array(['tuna', 'fred', 'shet', 'kahn'], dtype='<U7')

# Array indexing

In [399]:
name[0]

'tuna'

In [400]:
name[6]

'kahn'

In [401]:
name[0:3]

array(['tuna', 'toaster', 'courage'], dtype='<U7')

In [402]:
name[1::2]

array(['toaster', 'fred', 'shet'], dtype='<U7')

In [419]:
x = np.zeros((10,10))

In [420]:
x[0,:] = 1

In [421]:
x[-1, :] = 1

In [423]:
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [479]:
x = np.ones((10,10))

In [480]:
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [457]:
x[1:-1] = 0

In [459]:
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [481]:
x[1:-1, 1:-1] = 0

In [482]:
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# CREATE CHECKER and Football Ground

In [550]:
# CREATE CHECKER Board and Football Ground
# 1 0 1 0 1 0 1 0
a = np.ones((8,8), dtype=int)

In [551]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [552]:
# CHECKER - TASK
a[0::, 1::2] = 0
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [553]:
b = np.ones((8,8), dtype=int)

In [554]:
# football ground - TASK
'''
0 0 0 0 0 0 0 0 0 0
1 1 1 1 1 1 1 1 1 1
0 0 0 0 0 0 0 0 0 0
1 1 1 1 1 1 1 1 1 1
0 0 0 0 0 0 0 0 0 0
1 1 1 1 1 1 1 1 1 1
0 0 0 0 0 0 0 0 0 0
1 1 1 1 1 1 1 1 1 1
'''
b[0::2] = 0
b

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1]])